import DashboardLayout from "@/components/DashboardLayout";
import { ArrowLeft, ArrowRight, BookOpen, ExternalLink, ShieldCheck } from "lucide-react";
import { useState } from "react";

const articles = [
  { tag: "名称更新", title: "从 PCOS 到 PMOS：为什么疾病改名了？", summary: "新名称把关注点从“卵巢囊肿”扩展到内分泌、代谢、生殖与全生命周期健康。", minutes: 5, body: ["PMOS 是 Polyendocrine Metabolic Ovarian Syndrome 的缩写。名称更新强调：这不是简单的“卵巢长囊肿”，也不只是一种生育问题。", "名称变化首先影响理解与沟通，不代表需要重新诊断。就医和检索资料时，PMOS 与 PCOS 都可以使用。"] },
  { tag: "基础认识", title: "认识 PMOS：它不只是月经或生育问题", summary: "症状可能涉及月经、雄激素、代谢、皮肤、生殖和情绪健康。", minutes: 6, body: ["每个人的表现和困扰程度都不同。月经变化、痤疮、多毛、代谢风险与情绪困扰都值得被认真对待。", "风险信息的意义是帮助及时管理健康，而不是制造恐慌。"] },
  { tag: "就医诊断", title: "PMOS 如何诊断？为什么不能只看一次超声", summary: "诊断需综合症状与检查，并排除其他可能原因；不能依靠单项检查。", minutes: 6, body: ["诊断不是看见“囊肿”就可以。医生会结合月经、雄激素相关表现、必要检查与病史综合判断。", "网络问卷、一次 AMH 检测或一次超声，都不能替代专业评估。"] },
  { tag: "生活管理", title: "生活管理不等于减重：从可持续的小行动开始", summary: "健康饮食、身体活动与行为支持对整体健康有益，不以体重作为唯一标准。", minutes: 7, body: ["没有一种饮食方案适合所有人。选择自己愿意长期坚持、能照顾到文化和预算的方式更重要。", "从饭后散步十分钟、规律睡眠或一项小记录开始，比短期极端计划更可持续。"] },
  { tag: "心理健康", title: "情绪与身体形象：这些困扰值得被认真对待", summary: "焦虑、抑郁、身体形象和进食困扰都值得获得支持。", minutes: 6, body: ["心理健康也是 PMOS 管理的一部分。持续影响生活的低落、焦虑、羞耻或饮食困扰，都可以向专业人员求助。", "若出现自伤或自杀想法，请立即联系当地急救服务、危机热线或前往急诊。"] },
  { tag: "就医支持", title: "什么时候需要就医？把问题带到专业支持中", summary: "持续的月经、皮肤、代谢、生育或心理困扰，都可以成为就医的理由。", minutes: 6, body: ["把月经记录、用药清单、既往检查与最想确认的问题带去就诊，有助于沟通。", "本页面用于健康教育，不提供诊断、处方或个体化治疗建议。"] },
];

export default function EducationPage() {
  const [selected, setSelected] = useState<number | null>(null);
  const article = selected === null ? null : articles[selected];
  return <DashboardLayout><main className="mx-auto max-w-6xl space-y-7 pb-10">{article ? <article className="mx-auto max-w-3xl"><button onClick={() => setSelected(null)} className="mb-6 inline-flex items-center gap-2 text-sm text-[#bf6963]"><ArrowLeft className="h-4 w-4" />返回科普首页</button><p className="warm-kicker">{article.tag} · 约 {article.minutes} 分钟</p><h1 className="warm-title mt-2 text-3xl leading-tight sm:text-5xl">{article.title}</h1><p className="mt-5 text-lg leading-8 text-[#926d67]">{article.summary}</p><div className="mt-8 space-y-5 rounded-[1.75rem] bg-white p-6 shadow-[0_10px_28px_rgba(190,96,89,0.06)] sm:p-8">{article.body.map((paragraph, index) => <p key={index} className="text-base leading-8 text-[#704e4a]">{paragraph}</p>)}<div className="rounded-2xl bg-[#fff4ef] p-4 text-sm leading-6 text-[#895f59]"><ShieldCheck className="mr-1 inline h-4 w-4 text-[#d16c66]" />内容仅用于健康教育，不能替代医生的诊断、治疗或个体化建议。</div></div><a href="https://www.monash.edu/medicine/mchri/pcos/guideline" target="_blank" rel="noreferrer" className="mt-6 inline-flex items-center gap-2 text-sm font-medium text-[#bf6963]">查看国际循证指南 <ExternalLink className="h-4 w-4" /></a></article> : <><header className="rounded-[2rem] warm-gradient px-7 py-10 text-white sm:px-10"><p className="text-xs font-semibold tracking-[0.18em] text-white/75">PMOS · HEALTH EDUCATION</p><h1 className="mt-3 max-w-2xl font-serif text-4xl leading-tight sm:text-5xl">了解身体，从可靠的信息开始</h1><p className="mt-4 max-w-2xl text-sm leading-7 text-white/90">这里不替你下诊断，而是帮助你更有准备地照顾自己、与专业人员沟通。</p></header><section><div className="mb-4 flex items-end justify-between"><div><p className="warm-kicker">LEARNING PATH</p><h2 className="warm-title mt-1 text-3xl">从这里开始了解 PMOS</h2></div><BookOpen className="h-7 w-7 text-[#d6736d]" /></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{articles.map((item, index) => <button key={item.title} onClick={() => setSelected(index)} className="group rounded-[1.5rem] bg-white p-6 text-left shadow-[0_10px_28px_rgba(190,96,89,0.06)] transition hover:-translate-y-1"><span className="text-xs font-semibold text-[#d46d67]">{item.tag} · {item.minutes} 分钟</span><h3 className="warm-title mt-3 text-xl leading-snug">{item.title}</h3><p className="mt-3 text-sm leading-6 text-[#96716b]">{item.summary}</p><span className="mt-5 inline-flex items-center gap-1 text-sm font-medium text-[#c56561]">阅读全文 <ArrowRight className="h-4 w-4 transition group-hover:translate-x-1" /></span></button>)}</div></section><p className="rounded-2xl border border-[#f1d7d0] bg-[#fff8f5] p-4 text-sm leading-6 text-[#8d6963]">医疗提醒：若症状突然、严重或让你感到不安全，请优先联系当地急救服务或医疗机构。</p></>}</main></DashboardLayout>;
}
