import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { createTeam, getMyTeams, joinTeam, setProgressSharing } from "@/lib/teams";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Copy, HeartHandshake, LockKeyhole, Plus, ShieldCheck, UserPlus, UsersRound } from "lucide-react";
import { toast } from "sonner";

export default function TeamPage() {
  const queryClient = useQueryClient();
  const teamsQuery = useQuery({ queryKey: ["teams"], queryFn: getMyTeams });
  const refresh = () => queryClient.invalidateQueries({ queryKey: ["teams"] });
  const createMutation = useMutation({ mutationFn: createTeam, onSuccess: () => { toast.success("私密队伍已创建"); refresh(); }, onError: error => toast.error("创建失败", { description: error instanceof Error ? error.message : "请稍后重试" }) });
  const joinMutation = useMutation({ mutationFn: joinTeam, onSuccess: () => { toast.success("已加入陪伴队"); refresh(); }, onError: error => toast.error("加入失败", { description: "请确认邀请码是否正确" }) });
  const sharingMutation = useMutation({ mutationFn: ({ id, value }: { id: string; value: boolean }) => setProgressSharing(id, value), onSuccess: refresh, onError: () => toast.error("设置未保存") });

  const create = () => { const name = window.prompt("为你的私密队伍取个名字（最多 60 字）"); if (name?.trim()) createMutation.mutate(name.trim()); };
  const join = () => { const code = window.prompt("输入好友分享给你的邀请码"); if (code?.trim()) joinMutation.mutate(code.trim()); };
  const copy = async (code: string) => { await navigator.clipboard.writeText(code); toast.success("邀请码已复制，可发送给可信任的陪伴者"); };

  return <DashboardLayout><div className="mx-auto max-w-6xl space-y-6 pb-8">
    <header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="warm-kicker">TEAM · GENTLE TOGETHER</p><h1 className="warm-title mt-1 text-3xl sm:text-4xl">和懂你的人，一起慢慢来</h1><p className="mt-2 max-w-xl text-sm leading-6 text-[#9b746e]">队伍是私密的。只有获邀成员能看见队名和彼此选择分享的进度。</p></div><div className="flex gap-2"><Button onClick={join} variant="outline" className="rounded-full border-[#f3c9bf] bg-white/75 text-[#c66460]"><UserPlus className="mr-1.5 h-4 w-4" />加入队伍</Button><Button onClick={create} disabled={createMutation.isPending} className="rounded-full warm-gradient"><Plus className="mr-1.5 h-4 w-4" />创建队伍</Button></div></header>
    <section className="relative min-h-[22rem] overflow-hidden rounded-[2rem] bg-gradient-to-r from-[#f47f8a] via-[#f49a97] to-[#ffd8c8] px-7 py-9 text-white sm:px-9"><img src="/reference/team-tutu-banner.png" alt="团团和陪伴伙伴" className="absolute inset-y-0 right-0 hidden h-full w-[63%] object-cover object-center md:block" /><div className="absolute inset-0 bg-gradient-to-r from-[#ee7786] via-[#ee8490]/80 to-transparent" /><div className="relative z-10 max-w-md"><div className="inline-flex items-center gap-2 rounded-full border border-white/30 bg-white/10 px-3 py-1.5 text-xs"><LockKeyhole className="h-3.5 w-3.5" />你的节律，只分享给你愿意的人</div><h2 className="mt-7 font-serif text-4xl leading-tight">一起组队，<br />让陪伴更有力量</h2><p className="mt-4 text-sm leading-7 text-white/90">当你准备好，可以邀请值得信任的朋友、伴侣或家人，一起完成小小的健康行动。队伍数据将以你允许的范围私密展示。</p><div className="mt-6 flex flex-wrap gap-3"><Button onClick={join} className="rounded-full bg-white text-[#d36670] hover:bg-[#fff8f6]"><UserPlus className="mr-1.5 h-4 w-4" />邀请陪伴者</Button><Button onClick={() => window.location.assign("/checkin")} variant="outline" className="rounded-full border-white/40 bg-white/10 text-white hover:bg-white/20 hover:text-white">先完成今天的打卡</Button></div></div></section>
    <section className="grid gap-4 md:grid-cols-2">{teamsQuery.isLoading ? <p className="py-12 text-center text-sm text-[#9b746e] md:col-span-2">正在读取你的私密队伍……</p> : teamsQuery.data?.length ? teamsQuery.data.map(team => { const members = team.team_members ?? []; const mine = members.find(member => member.user_id === team.viewer_id); return <article key={team.id} className="warm-surface rounded-[1.75rem] p-6"><div className="flex items-start justify-between gap-3"><div><p className="warm-kicker">PRIVATE CIRCLE</p><h2 className="warm-title mt-1 text-2xl">{team.name}</h2><p className="mt-2 text-sm text-[#9c756f]">{members.length} 位成员 · 没有排名</p></div><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-[#fff0eb] text-[#d46e68]"><HeartHandshake className="h-5 w-5" /></span></div><div className="mt-5 rounded-2xl bg-[#fff7f4] p-4"><p className="text-xs text-[#a47d77]">邀请可信任的人加入</p><div className="mt-2 flex items-center gap-2"><code className="min-w-0 flex-1 truncate rounded-lg bg-white px-3 py-2 text-sm font-semibold tracking-wider text-[#8f5955]">{team.invite_code}</code><Button size="icon" variant="outline" onClick={() => void copy(team.invite_code)} className="shrink-0 rounded-lg border-[#f0d5ce] text-[#bd625e]"><Copy className="h-4 w-4" /></Button></div></div><label className="mt-5 flex cursor-pointer items-center justify-between gap-4 text-sm text-[#805c57]"><span><b>分享今日完成进度</b><small className="mt-1 block text-xs text-[#a47d77]">仅分享完成数量，不共享具体健康记录</small></span><input type="checkbox" checked={mine?.share_progress ?? false} onChange={event => sharingMutation.mutate({ id: team.id, value: event.target.checked })} className="h-4 w-4 accent-[#d46e68]" /></label></article>; }) : <div className="warm-surface rounded-[1.75rem] p-9 text-center md:col-span-2"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-[#ffe7df] text-[#d47068]"><HeartHandshake className="h-6 w-6" /></div><h2 className="warm-title mt-4 text-2xl">从一位陪伴者开始</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-[#9d7770]">创建队伍后可分享邀请码；或输入收到的邀请码加入。随时可以关闭自己的进度分享。</p><Button onClick={create} className="mt-5 rounded-full warm-gradient"><Plus className="mr-1.5 h-4 w-4" />创建我的队伍</Button></div>}</section>
    <section className="rounded-[1.75rem] border border-[#f6e1db] bg-[#fff5f0] p-6"><div className="flex items-center gap-2 text-[#d17168]"><ShieldCheck className="h-5 w-5" /><p className="text-sm font-semibold">队伍的隐私边界</p></div><p className="mt-3 text-sm leading-6 text-[#8e6963]">邀请码只应发送给你信任的人。经期、症状、具体记录默认不向队友公开；本期仅允许你自主分享“今日完成数量”。</p></section>
  </div></DashboardLayout>;
}
